#!/bin/bash
# Write a script which monitors the modifications made to the
# /etc/crontab file and sends an e-mail to root if the file is modified.
# Create a scheduled task to run this script everyday at midnight
#
# insert in crontab -e
# 0 0 * * * /path/to/script
SUM='md5sum /etc/crontab | cut -d " " -f 1'
NEWSUM='cat /root/cronhash'

if [ "$SUM" != "$NEWSUM" ]
then
	md5sum /etc/crontab | cut -d " " -f 1 > /root/cronhash
	mail -s "The crontab file was modified" root < /etc/crontab
fi
#
# crontab -e lets us edit the scheduled task running with cron
# 0 0 * * * means the script will run everyday at midnight
# in order: minute | hour | day of month | month | day of week
